language: ruby
bundler_args: ''
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: jruby-head
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/4.0.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/4.0.gemfile
    - rvm: jruby-18mode
      gemfile: gemfiles/4.0.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/4.0.gemfile
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile